export const SeccretKey = {
	FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
	FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
	FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
	FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
	FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
	FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
	FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
	VIET_MAP_KEY: process.env.NEXT_PUBLIC_VIET_MAP_KEY,
	TINYMCE_API_KEY: process.env.NEXT_PUBLIC_TINYMCE_API_KEY,
}

